- name: Prepare yocto layers
  hosts: all
  connection: local
  vars:
    dest_dir: "{{ clonedir }}"
    machine: "{{ board | default('raspberrypi4-64') }}"
    project_dir: "{{ playbook_dir }}"
    poky_version: "kirkstone"
    oe_version: "kirkstone"
    rpi_version: "kirkstone"
    qt_version: "v6.4.2"
  tasks:
    - name: Create base directory
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: directory
        mode: '755'

    - name: "Clone poky"
      ansible.builtin.git:
        repo: git://git.yoctoproject.org/poky.git
        dest: "{{ dest_dir }}/poky"
        version: "{{ poky_version }}"
        force: true
        accept_hostkey: true

    - name: "Clone meta-openembedded layer"
      ansible.builtin.git:
        repo: git://git.openembedded.org/meta-openembedded
        dest: "{{ dest_dir }}/poky/meta-openembedded/"
        version: "{{ oe_version }}"
        force: true
        accept_hostkey: true

    - name: "Clone meta-raspberrypi layer"
      ansible.builtin.git:
        repo: git://git.yoctoproject.org/meta-raspberrypi.git
        dest: "{{ dest_dir }}/poky/meta-raspberrypi/"
        version: "{{ rpi_version }}"
        force: true
        accept_hostkey: true

    - name: "Create machine directory with conf directory"
      ansible.builtin.file:
        path: "{{ dest_dir }}/build_{{ machine }}/conf"
        state: directory
        mode: '755'

    - name: "Copy local.conf file"
      ansible.builtin.copy:
        src: "{{ project_dir }}/examples/localconf/{{ machine }}_local.conf"
        dest: "{{ dest_dir }}/build_{{ machine }}/conf/local.conf"
        remote_src: true
        mode: '644'

    - name: "Copy bblayers.conf file"
      ansible.builtin.copy:
        src: "{{ project_dir }}/examples/bblayers/{{ machine }}_bblayers.conf"
        dest: "{{ dest_dir }}/build_{{ machine }}/conf/bblayers.conf"
        remote_src: true
        mode: '644'

    - name: "Configure bblayers for proper path"
      ansible.builtin.replace:
        path: "{{ dest_dir }}/build_{{ machine }}/conf/bblayers.conf"
        regexp: "[$][{]HOME[}]/yocto"
        replace: "{{ dest_dir }}"

    - name: "Add project clone directory to bblayers"
      ansible.builtin.lineinfile:
        path: "{{ dest_dir }}/build_{{ machine }}/conf/bblayers.conf"
        line: "    {{ project_dir }} \\"
        insertafter: "{{ dest_dir }}/poky/meta-poky"
